CREATE TABLE users(
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      email VARCHAR(255) NOT NULL UNIQUE,
                      password VARCHAR(255) NOT NULL,
                      full_name VARCHAR(255) NOT NULL,
                      role VARCHAR(50) NOT NULL,
                      active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE complaints(
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           rma_number VARCHAR(255) NOT NULL UNIQUE,
                           product_type VARCHAR(255),
                           description TEXT,
                           status VARCHAR(50) NOT NULL DEFAULT 'NEW',
                           assigned_to_id BIGINT,
                           assigned_date DATE,
                           pickup_confirmed DATE,
                           repair_description TEXT,
                           repair_confirmed DATE,
                           return_confirmed DATE,
                           sent_to_client DATE,
                           delivery_address VARCHAR(255),
                           insurance_amount NUMERIC(19, 2),
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP,

                           CONSTRAINT fk_complaints_assigned_to FOREIGN KEY (assigned_to_id) REFERENCES users(id)
);